cantry = ['Africa', 'Goa', 'Mexico', 'USA', 'Britain']
print(cantry)
print(sorted(cantry))
print(cantry)
print(sorted(cantry, reverse=True))
print(cantry)
cantry.reverse()
print(cantry)
cantry.reverse()
print(cantry)
cantry.sort()
print(cantry)
cantry.sort(reverse=True)
print(cantry)
